// Adapted from SDK-Decentralized-Value f84d825 scripts/sync-contract.ts.
// The current monorepo is canonical; no external checkout or duplicate OpenAPI snapshot is used.
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import { format, resolveConfig } from "prettier";
import ts from "typescript";
import { normalizedText, syncGeneratedOutputs } from "./generated-output";

const canonicalSources = [
  "openapi/frontier-v1.yaml",
  "openapi/generated/cli.schemas.json",
  "openapi/generated/cli.contract.json",
  "apps/api/src/plan6-competition.ts",
  "apps/api/src/cli-manifest.ts",
  "apps/api/src/cli-response-schemas.ts",
  "packages/shared/src/cli.ts",
  "packages/shared/src/multiobjective.ts",
  "packages/disaster-response/src/index.ts",
  "packages/rescue-room/src/index.ts",
] as const;

/** Copy complete declarations, not JSON Schema, so cross-field refinements survive. */
export function extractRequestSchemas(sourceText: string): string {
  const source = ts.createSourceFile(
    "plan6-competition.ts",
    sourceText,
    ts.ScriptTarget.Latest,
    true,
  );
  const names = new Set([
    "supplierIdSchema",
    "disasterResponseStrategySchema",
    "plan6SubmissionSchema",
  ]);
  const declarations = source.statements.filter(
    (statement) =>
      ts.isVariableStatement(statement) &&
      statement.declarationList.declarations.some(
        (declaration) => ts.isIdentifier(declaration.name) && names.has(declaration.name.text),
      ),
  );
  if (
    declarations.length !== names.size ||
    declarations.some(
      (statement) =>
        !ts.isVariableStatement(statement) || statement.declarationList.declarations.length !== 1,
    )
  )
    throw new Error("Canonical request schemas changed; review the generator");
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  return (
    '// Generated by scripts/sync-contract.ts from the canonical API. Do not edit.\nimport { z } from "zod";\n\n' +
    declarations
      .map((statement) => printer.printNode(ts.EmitHint.Unspecified, statement, source))
      .join("\n\n") +
    "\n"
  );
}

export async function generateSdkContract(root: string): Promise<Map<string, string>> {
  const outputs = new Map<string, string>();
  const config = await resolveConfig(resolve(root, "package.json"));
  const output = async (path: string, content: string, parser: "typescript" | "json") => {
    outputs.set(path, await format(content, { ...config, parser }));
  };
  const source = await readFile(resolve(root, "apps/api/src/plan6-competition.ts"), "utf8");
  await output(
    "packages/sdk/src/generated/request-schemas.ts",
    extractRequestSchemas(source),
    "typescript",
  );
  await output(
    "packages/sdk/src/generated/api-types.ts",
    astToString(await openapiTS(pathToFileURL(resolve(root, "openapi/frontier-v1.yaml")))),
    "typescript",
  );

  // Only deterministic public Practice; no server, private credentials, AI or RPC is invoked.
  const manifests = await import(pathToFileURL(resolve(root, "apps/api/src/cli-manifest.ts")).href);
  const disaster = await import(
    pathToFileURL(resolve(root, "packages/disaster-response/src/index.ts")).href
  );
  const competition = await import(
    pathToFileURL(resolve(root, "apps/api/src/plan6-competition.ts")).href
  );
  const rescue = await import(
    pathToFileURL(resolve(root, "packages/rescue-room/src/index.ts")).href
  );
  for (const id of ["disaster-response", "rescue-room"]) {
    const manifest = manifests.cliArenaManifest(id, {
      storage: "ephemeral-memory",
      authenticationAvailable: true,
    });
    const artifact = manifest.artifact.sample;
    const raw =
      id === "disaster-response"
        ? {
            state: "measured",
            ...disaster.evaluateDisasterResponseStrategy(artifact),
            inputHash: competition.disasterResponseInputHash(artifact),
          }
        : {
            state: "simulated",
            strategyState: "deterministic-rules",
            paymentState: "game-credits",
            ...rescue.evaluateRescueDoctrinePracticeEpisode(artifact, manifest.episodes[0].id),
          };
    await output(`tests/fixtures/${id}.json`, JSON.stringify({ manifest, raw }, null, 2), "json");
  }
  const hashes: Record<string, string> = {};
  for (const path of canonicalSources) {
    hashes[path] = createHash("sha256")
      .update(normalizedText(await readFile(resolve(root, path), "utf8")))
      .digest("hex");
  }
  const packageJson = JSON.parse(await readFile(resolve(root, "package.json"), "utf8"));
  await output(
    "packages/sdk/src/generated/provenance.json",
    JSON.stringify({
      schemaVersion: "1",
      generator: {
        "openapi-typescript": packageJson.devDependencies["openapi-typescript"],
        typescript: ts.version,
      },
      // Direct generator inputs only, not a transitive evaluator/runtime attestation.
      sources: hashes,
    }),
    "json",
  );
  return outputs;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const root = resolve(import.meta.dirname, "..");
  const check = process.argv.includes("--check");
  await syncGeneratedOutputs(root, await generateSdkContract(root), check);
  console.log(
    check ? "SDK contract and fixtures are current." : "SDK contract and fixtures synchronized.",
  );
}
