import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
import solc from "solc";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceName = "SubmissionDecoders.sol";
const source = await readFile(resolve(packageRoot, "contracts", sourceName), "utf8");
const input = {
  language: "Solidity",
  sources: { [sourceName]: { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    evmVersion: "cancun",
    metadata: { bytecodeHash: "none", appendCBOR: false },
    outputSelection: { "*": { "*": ["evm.deployedBytecode.object"] } },
  },
};
const output = JSON.parse(solc.compile(JSON.stringify(input))) as {
  errors?: { severity: string; formattedMessage: string }[];
  contracts?: Record<string, Record<string, { evm: { deployedBytecode: { object: string } } }>>;
};
const errors = output.errors?.filter((error) => error.severity === "error") ?? [];
if (errors.length > 0) throw new Error(errors.map((error) => error.formattedMessage).join("\n"));

const contracts = output.contracts?.[sourceName];
if (!contracts) throw new Error("solc returned no contracts");
const names = ["AbiDecoder", "PackedDecoder", "DictionaryDecoder"] as const;
function runtimeBytecode(name: (typeof names)[number]) {
  const contract = contracts?.[name];
  if (!contract) throw new Error(`solc returned no ${name} contract`);
  return contract.evm.deployedBytecode.object;
}
const lines = [
  "// Generated by pnpm --filter @frontier/calldata-compression compile:codecs.",
  `export const codecCompiler = ${JSON.stringify({ solc: solc.version(), evmVersion: "cancun", optimizerRuns: 200 })} as const;`,
  "export const codecRuntimeBytecode = {",
  ...names.map((name) => `  ${name}: \"0x${runtimeBytecode(name)}\",`),
  "} as const;",
  "",
];
const generated = await format(lines.join("\n"), { parser: "typescript" });
await writeFile(resolve(packageRoot, "src", "runtime-bytecode.ts"), generated, "utf8");
